### ISSUE TITLE
How to predict the output of test data for task1

### ISSUE THREAD

**Issue by NNNNNaaaaaa** [arghosh/NeurIPSEducation2020#1]
From the code, I understand you mask the labels of valid and test data to 0, so when inference, do you still mask valid data?And is it possible to public  the inference code? PS.  I am new to Pytorch and interested in your solution of task1, Thank 有

**Comment by arghosh** [comment]
testing_flag = (1-test_mask)*valid_mask in line 34, and test_preds.append(output[testing_flag == 1])        test_targets.append(target[testing_flag == 1]) should give you testing samples. 

Suppose a student has 5 interaction (index 0-4), index 0 is validation point and index 1 is testing point, then the masks are (padded to length 8):
test_mask = [1,0,1,1,1,0,0,0]
valid_mask = [0,1,1,1,1,0,0,0]
